# global:
#   scrape_interval: 15s

# scrape_configs:
#   - job_name: 'flask_app'
#     static_configs:
#       - targets: ['host.docker.internal:5000']
docker volume create prometheus-data
docker run \
    -p 9090:9090 \
    -v /path/to/prometheus.yml:/etc/prometheus/prometheus.yml \
    prom/prometheus